/**
 * Background service worker for handling AI requests via Groq.
 */

const GROQ_API_KEY = "REDACTED";

// Handle messages from the popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "summarize") {
    handleSummarization(request.data)
      .then(summary => sendResponse({ success: true, summary }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true; // Keep channel open
  }
});

/**
 * Calls the Groq API to summarize content.
 */
async function handleSummarization(data) {
  const { textContent, title } = data;
  
  // Use the provided API key
  const API_KEY = GROQ_API_KEY;
  const API_URL = "https://api.groq.com/openai/v1/chat/completions";

  const prompt = `
    You are a professional research assistant. Summarize the following webpage content titled "${title}".
    
    Please provide:
    1. A concise, high-level overview (1-2 sentences).
    2. A bulleted list of 3-5 key takeaways.
    3. 2-3 important insights or "pro tips" derived from the content.
    
    Format the output in clear, structured markdown. Use bolding for emphasis.
    If the content is too short or not an article, just provide a brief summary.
    
    Content:
    ${textContent.substring(0, 15000)} // Truncate to avoid token limits
  `;

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${API_KEY}`,
      },
      body: JSON.stringify({
        model: "llama-3.3-70b-versatile",
        messages: [
          {
            role: "system",
            content: "You are a professional research assistant specializing in clear, concise summaries."
          },
          {
            role: "user",
            content: prompt
          }
        ],
        temperature: 0.5,
        max_tokens: 1024,
      })
    });

    const result = await response.json();

    if (!response.ok) {
      const errorMsg = result.error?.message || "Groq API request failed";
      throw new Error(errorMsg);
    }

    if (!result.choices || result.choices.length === 0) {
      throw new Error("No summary generated by Groq.");
    }

    const summaryText = result.choices[0].message.content;
    return summaryText;

  } catch (error) {
    console.error("Summarization error:", error);
    throw error;
  }
}
