/**
 * Background service worker for handling AI requests.
 */

// Handle messages from the popup
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "summarize") {
    handleSummarization(request.data)
      .then(summary => sendResponse({ success: true, summary }))
      .catch(error => sendResponse({ success: false, error: error.message }));
    return true; // Keep channel open
  }
});

/**
 * Calls the Gemini API to summarize content.
 */
async function handleSummarization(data) {
  const { textContent, title } = data;
  
  // Get API key from storage
  const settings = await chrome.storage.sync.get(['apiKey']);
  if (!settings.apiKey) {
    throw new Error("API Key missing. Please set it in Settings.");
  }

  const API_KEY = settings.apiKey;
  const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${API_KEY}`;

  const prompt = `
    You are a professional research assistant. Summarize the following webpage content titled "${title}".
    
    Please provide:
    1. A concise, high-level overview (1-2 sentences).
    2. A bulleted list of 3-5 key takeaways.
    3. 2-3 important insights or "pro tips" derived from the content.
    
    Format the output in clear, structured markdown. Use bolding for emphasis.
    If the content is too short or not an article, just provide a brief summary.
    
    Content:
    ${textContent}
  `;

  try {
    const response = await fetch(API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [{
          parts: [{
            text: prompt
          }]
        }]
      })
    });

    const result = await response.json();

    if (!response.ok) {
      const errorMsg = result.error?.message || "API request failed";
      throw new Error(errorMsg);
    }

    if (!result.candidates || result.candidates.length === 0) {
      throw new Error("No summary generated by the AI.");
    }

    const summaryText = result.candidates[0].content.parts[0].text;
    return summaryText;

  } catch (error) {
    console.error("Summarization error:", error);
    throw error;
  }
}
